### ISSUE TITLE
Some inconsistencies and remarks.

### ISSUE THREAD

**Issue by Koepel** [closedcube/ClosedCube_I2C_Arduino#1]
The 'int' is 2 bytes in a Arduino Uno. The library assumes that 'int' is 4 bytes.

The function readWord() returns a "short". But a "word" is often unsigned and a "short integer" is a signed integer.

To read data from a register, the names could be like this: readByte(), readS16(), readU16(), readU32(), and so on.

The library uses a repeated start between setting the register address and reading the data from a sensor. That is probably okay. Every modern sensor should support a repeated start.

The Arduino Wire library has already a function that writes the register address and after that reads the data. It is a overloaded Wire.requestFrom() function that can do that with a single call to Wire.requestFrom(). It is well supported, but not documented yet.

The ClosedCube::Driver::I2CDevice::readBytes() is used to retrieve the data. However, there is another function with the "stop" parameter that has beginTransmission() and endTransmission(). That is something completely different, but they do have the same name.

In the function readInt(), the 8-bit chars are shifted to the left, instead of shifting a 4-byte variable. It is not nice to shift a 8-bit variable 24 times to the left. The char buf[4] are signed characters, I think it is easier if they are unsigned.

**Comment by closedcube** [comment]
Hello,

Thank you for your details.
We release a new version into public GitHub repo.

Kind regards,
ClosedCube
