### ISSUE TITLE
Compile error when using 2 different sensors

### ISSUE THREAD

**Issue by wijnsema** [closedcube/ClosedCube_I2C_Arduino#4]
When I use a TSYS01 and a STS35 in the same project I receive a comilation error:

> error: redefinition of 'class ClosedCube::Driver::I2CDevice'

Possible cause: Something goes wrong with the 

`#ifndef _CLOSEDCUBE_I2C_H`

it is not closed correctly. If you use just 1 sensor this is not a problem, with 2 or more an error shows up.

**Comment by closedcube** [comment]
Thank you for the feedback.
The issue has been fixed.
